### ISSUE TITLE
Need some readme file like hdmilight-v2

### ISSUE THREAD

**Issue by xfce** [esar/hdmilight-v3#1]
Hi @esar , 
    So i think I can fellow the v3 hdmilight.
Now for FPGA I can use xilinx ise got the fpga/HdmilightTop.bit
and what is the next steps?
When got the v3 hardware, Plug into  PC usb and In the top level directory, type
make fpga_program
fpga_flash
make v2_all

**Comment by esar** [comment]
I've updated the makefiles to make them a bit more user friendly and updated the README with the current instructions.

**Comment by xfce** [comment]
@esar OK, Thanks.
I will use your board, Does the v3.1 gerber file good for manufacture.

**Comment by esar** [comment]
I don't know yet, I'm waiting for boards to arrive so that I can test it. Hopefully they won't take too long to arrive.

**Comment by xfce** [comment]
OK, thanks. I have order 5pcs boards use v3.1 gerber, and will fellow with you^-^

**Comment by esar** [comment]
@xfce My boards arrived and I spent the weekend populating and testing one. It looks like the PCB design is ok, I've not found any issues with that yet.
In case you find it useful, I've added a wiki page detailing the steps that I took to test the board:
https://github.com/esar/hdmilight-v3/wiki/V3.1-Board-Testing-Notes

**Comment by xfce** [comment]
@esar  OK , Thanks. It is a good news.
Actually , Mine have also arrived, and will fellow your wiki this weekend.
Bellow is the PCB, left is HDMILIGHT V3.1, right is my other project PCB^-^

![](https://i.imgur.com/vjFFk1C.jpg)

**Comment by xfce** [comment]
@esar Hi, I have solder most of the components.  
![](https://i.imgur.com/Du2lkAe.jpg)

And also I still want to try the HDMILIGHT V2.0, as it seems much simple , so I have draw the schematics , could you please help me to review it, thanks.

**Comment by esar** [comment]
@xfce Cool, looking good!

I've only had time to take a quick look at your schematic, so I've not checked all the connections, but what I have checked looks good. I just have a couple of things to mention:
1) Xilinx recommend a strong pull up on the DONE pin. I can't remember for sure and don't have the Papilio Pro schematic to hand, but I'm guessing that you're copying what was done there, in which case it should be fine. I had no problem using the Papilio board. Here's where Xilinx recommend it: https://www.xilinx.com/support/answers/35002.html

2) The data and clock pairs on the in and out side of the ESD protection chip need to be connected together. There needs to be traces under the chip as the chip doesn't pass them through, it just clamps them. Maybe the software you're using allows you to route them without them connected in the schematic? 

3) You don't need the eeprom attached to the FTDI chip. At least JTAG and serial both work without it when using openocd. I've not tried without it when using the Papilio loader software that I used with v2 though.

4) I don't know how familiar you are with FPGAs... keep in mind that you can be quite flexible with the FPGA pins used to connect to the ADV7611. You can change the mapping in the .ucf file in the fpga directory. It's nice to be able to swap them around sometimes when it makes routing the board easier. The only pin that is really restricted is the LLC pin from the ADV7611. This is the video clock and it should be kept on one of the FPGA pins that is connected to a global clock network within the FPGA (the ones with GCLK in their pin name).
