### ISSUE TITLE
LED strips connection order

### ISSUE THREAD

**Issue by xfce** [esar/hdmilight-v3#3]
Hi @esar 
    If I want to change the LED strips connection order, for example from left(bottom to top)->top(left to right)->right(top to bottom)->bottom(right to left), how can I use the configgenerate? Thanks

**Comment by esar** [comment]
@xfce I've never used the ConfigGenerate script. It was written by someone else and I added it to the repo in case anyone else found it useful. 

I've always written the config files by hand. I can describe how the configuration files work if that would be useful.

**Comment by xfce** [comment]
OK, right now， I am use the ConfigGenerate script, it works well, but I can't understand the detail, also it says the script can't handle LEDs more than 512, and have the fixed connect order.
So, could you please explain how to write arer.conf and output_n.conf, thanks @esar

**Comment by esar** [comment]
@xfce I've added a new file describing how the configuration files work:
https://github.com/esar/hdmilight-v3/blob/master/docs/configuration.md

Let me know if anything doesn't make sense or needs clarifying

**Comment by xfce** [comment]
Hi @esar , 
 I have read the configuration.md, and write my area.conf and output, please help to review, thanks
LED strip from top(left-right:32 LED)-right(top-bottom:19 LED)-bottom(right-left:32 LED)-left(bottom-top:19 LED)

### **area.conf**
 LED strip start：Top Row running left to right： 32 LEDs
 xmin  xmax  ymin  ymax  divshift 
  0     0     27    34    3       
  0     1     27    34    3         
  2     3     27    34    3        
  4     5     27    34    3        
  6     7     27    34    3        
  8     9     27    34    3        
  10    11    27    34    3        
  12    13    27    34    3       
  14    15    27    34    3        
  16    17    27    34    3        
  18    19    27    34    3       
  20    21    27    34    3        
  22    23    27    34    3        
  24    25    27    34    3        
  26    27    27    34    3        
  28    29    27    34    3       
  30    31    27    34    3        
  32    33    27    34    3        
  34    35    27    34    3        
  36    37    27    34    3        
  38    39    27    34    3        
  40    41    27    34    3        
  42    43    27    34    3        
  44    45    27    34    3        
  46    47    27    34    3        
  48    49    27    34    3        
  50    51    27    34    3        
  52    53    27    34    3        
  54    55    27    34    3        
  56    57    27    34    3        
  58    58    27    34    3        
  59    59    27    34    3   
 Right Column running top to bottom ： 19 LEDS
 xmin  xmax  ymin  ymax  divshift 
  52    59    33    33    3       
  52    59    32    33    3        
  52    59    30    31    3        
  52    59    28    29    3        
  52    59    26    27    3       
  52    59    24    25    3        
  52    59    22    23    3        
  52    59    20    21    3        
  52    59    18    19    3        
  52    59    16    17    3        
  52    59    14    15    3        
  52    59    12    13    3        
  52    59    10    11    3        
  52    59    8     9     3        
  52    59    6     7     3        
  52    59    4     5     3        
  52    59    2     3     3        
  52    59    0     1     3        
  52    59    0     0     3        
Bottom Row running right to left : 32 LEDS
xmin  xmax  ymin  ymax  divshift 
  59    59    27    34    3        
  58    59    27    34    3       
  56    57    27    34    3        
  54    55    27    34    3        
  52    53    27    34    3        
  50    51    27    34    3        
  48    49    27    34    3        
  46    47    27    34    3        
  44    45    27    34    3        
  42    43    27    34    3        
  40    41    27    34    3       
  38    39    27    34    3       
  36    37    27    34    3      
  34    35    27    34    3        
  32    33    27    34    3       
  30    31    27    34    3       
  28    29    27    34    3       
  26    27    27    34    3       
  24    25    27    34    3        
  22    23    27    34    3        
  20    21    27    34    3       
  18    19    27    34    3       
  16    17    27    34    3       
  14    15    27    34    3        
  12    13    27    34    3        
  10    11    27    34    3        
  8     9     27    34    3       
  6     7     27    34    3        
  4     5     27    34    3       
  2     3     27    34    3        
  0     1     27    34    3        
  0     0     27    34    3        
Left Column running bottom to top :19 LEDS
xmin  xmax  ymin  ymax  divshift
  0     7     0     0     3 
  0     7     0     1     3        
  0     7     2     3     3        
  0     7     4     5     3        
  0     7     6     7     3        
  0     7     8     9     3        
  0     7     10    11    3        
  0     7     12    13    3        
  0     7     14    15    3        
  0     7     16    17    3        
  0     7     18    19    3        
  0     7     20    21    3        
  0     7     22    23    3      
  0     7     24    25    3       
  0     7     26    27    3      
  0     7     28    29    3       
  0     7     30    31    3        
  0     7     32    33    3        
  0     7     34    34    3        

###    **output.conf**
index    area    colour    gamma    enable
      0       0         1        1         1
      1       1         1        1         1
      2       2         1        1         1
      3       3         1        1         1
      4       4         1        1         1
      5       5         1        1         1
      6       6         1        1         1
      7       7         1        1         1
      8       8         1        1         1
      9       9         1        1         1
     10      10         1        1         1
     11      11         1        1         1
     12      12         1        1         1
     13      13         1        1         1
     14      14         1        1         1
     15      15         1        1         1
     16      16         1        1         1
     17      17         1        1         1
     18      18         1        1         1
     19      19         1        1         1
     20      20         1        1         1
     21      21         1        1         1
     22      22         1        1         1
     23      23         1        1         1
     24      24         1        1         1
     25      25         1        1         1
     26      26         1        1         1
     27      27         1        1         1
     28      28         1        1         1
     29      29         1        1         1
     30      30         1        1         1
     31      31         1        1         1
     32      32         1        1         1
     33      33         1        1         1
     34      34         1        1         1
     35      35         1        1         1
     36      36         1        1         1
     37      37         1        1         1
     38      38         1        1         1
     39      39         1        1         1
     40      40         1        1         1
     41      41         1        1         1
     42      42         1        1         1
     43      43         1        1         1
     44      44         1        1         1
     45      45         1        1         1
     46      46         1        1         1
     47      47         1        1         1
     48      48         1        1         1
     49      49         1        1         1
     50      50         1        1         1
     51      51         1        1         1
     52      52         1        1         1
     53      53         1        1         1
     54      54         1        1         1
     55      55         1        1         1
     56      56         1        1         1
     57      57         1        1         1
     58      58         1        1         1
     59      59         1        1         1
     60      60         1        1         1
     61      61         1        1         1
     62      62         1        1         1
     63      63         1        1         1
     64      64         1        1         1
     65      65         1        1         1
     66      66         1        1         1
     67      67         1        1         1
     68      68         1        1         1
     69      69         1        1         1
     70      70         1        1         1
     71      71         1        1         1
     72      72         1        1         1
     73      73         1        1         1
     74      74         1        1         1
     75      75         1        1         1
     76      76         1        1         1
     77      77         1        1         1
     78      78         1        1         1
     79      79         1        1         1
     80      80         1        1         1
     81      81         1        1         1
     82      82         1        1         1
     83      83         1        1         1
     84      84         1        1         1
     85      85         1        1         1
     86      86         1        1         1
     87      87         1        1         1
     88      88         1        1         1
     89      89         1        1         1
     90      90         1        1         1
     91      91         1        1         1
     92      92         1        1         1
     93      93         1        1         1
     94      94         1        1         1
     95      95         1        1         1
     96      96         1        1         1
     97      97         1        1         1
     98      98         1        1         1
     99      99         1        1         1
    100     100         1        1         1
    101     101         1        1         1

Remaining LEDs are disabled
    102       0         1        1         1
    103       0         1        1         1
    104       0         1        1         1
    105       0         1        1         1
    106       0         1        1         1
    107       0         1        1         1
    108       0         1        1         1
    109       0         1        1         1
    110       0         1        1         1
    111       0         1        1         1
    112       0         1        1         1
    113       0         1        1         1
    114       0         1        1         1
    115       0         1        1         1
    116       0         1        1         1
    117       0         1        1         1
    118       0         1        1         1
    119       0         1        1         1
    120       0         1        1         1
    121       0         1        1         1
    122       0         1        1         1
    123       0         1        1         1
    124       0         1        1         1
    125       0         1        1         1
    126       0         1        1         1
    127       0         1        1         1
    128       0         1        1         1
    129       0         1        1         1
    130       0         1        1         1
    131       0         1        1         1
    132       0         1        1         1
    133       0         1        1         1
    134       0         1        1         1
    135       0         1        1         1
    136       0         1        1         1
    137       0         1        1         1
    138       0         1        1         1
    139       0         1        1         1
    140       0         1        1         1
    141       0         1        1         1
    142       0         1        1         1
    143       0         1        1         1
    144       0         1        1         1
    145       0         1        1         1
    146       0         1        1         1
    147       0         1        1         1
    148       0         1        1         1
    149       0         1        1         1
    150       0         1        1         1
    151       0         1        1         1
    152       0         1        1         1
    153       0         1        1         1
    154       0         1        1         1
    155       0         1        1         1
    156       0         1        1         1
    157       0         1        1         1
    158       0         1        1         1
    159       0         1        1         1
    160       0         1        1         1
    161       0         1        1         1
    162       0         1        1         1
    163       0         1        1         1
    164       0         1        1         1
    165       0         1        1         1
    166       0         1        1         1
    167       0         1        1         1
    168       0         1        1         1
    169       0         1        1         1
    170       0         1        1         1
    171       0         1        1         1
    172       0         1        1         1
    173       0         1        1         1
    174       0         1        1         1
    175       0         1        1         1
    176       0         1        1         1
    177       0         1        1         1
    178       0         1        1         1
    179       0         1        1         1
    180       0         1        1         1
    181       0         1        1         1
    182       0         1        1         1
    183       0         1        1         1
    184       0         1        1         1
    185       0         1        1         1
    186       0         1        1         1
    187       0         1        1         1
    188       0         1        1         1
    189       0         1        1         1
    190       0         1        1         1
    191       0         1        1         1
    192       0         1        1         1
    193       0         1        1         1
    194       0         1        1         1
    195       0         1        1         1
    196       0         1        1         1
    197       0         1        1         1
    198       0         1        1         1
    199       0         1        1         1
    200       0         1        1         1
    201       0         1        1         1
    202       0         1        1         1
    203       0         1        1         1
    204       0         1        1         1
    205       0         1        1         1
    206       0         1        1         1
    207       0         1        1         1
    208       0         1        1         1
    209       0         1        1         1
    210       0         1        1         1
    211       0         1        1         1
    212       0         1        1         1
    213       0         1        1         1
    214       0         1        1         1
    215       0         1        1         1
    216       0         1        1         1
    217       0         1        1         1
    218       0         1        1         1
    219       0         1        1         1
    220       0         1        1         1
    221       0         1        1         1
    222       0         1        1         1
    223       0         1        1         1
    224       0         1        1         1
    225       0         1        1         1
    226       0         1        1         1
    227       0         1        1         1
    228       0         1        1         1
    229       0         1        1         1
    230       0         1        1         1
    231       0         1        1         1
    232       0         1        1         1
    233       0         1        1         1
    234       0         1        1         1
    235       0         1        1         1
    236       0         1        1         1
    237       0         1        1         1
    238       0         1        1         1
    239       0         1        1         1
    240       0         1        1         1
    241       0         1        1         1
    242       0         1        1         1
    243       0         1        1         1
    244       0         1        1         1
    245       0         1        1         1
    246       0         1        1         1
    247       0         1        1         1
    248       0         1        1         1
    249       0         1        1         1
    250       0         1        1         1
    251       0         1        1         1
    252       0         1        1         1
    253       0         1        1         1
    254       0         1        1         1
    255       0         1        1         1
    256       0         1        1         1
    257       0         1        1         1
    258       0         1        1         1
    259       0         1        1         1
    260       0         1        1         1
    261       0         1        1         1
    262       0         1        1         1
    263       0         1        1         1
    264       0         1        1         1
    265       0         1        1         1
    266       0         1        1         1
    267       0         1        1         1
    268       0         1        1         1
    269       0         1        1         1
    270       0         1        1         1
    271       0         1        1         1
    272       0         1        1         1
    273       0         1        1         1
    274       0         1        1         1
    275       0         1        1         1
    276       0         1        1         1
    277       0         1        1         1
    278       0         1        1         1
    279       0         1        1         1
    280       0         1        1         1
    281       0         1        1         1
    282       0         1        1         1
    283       0         1        1         1
    284       0         1        1         1
    285       0         1        1         1
    286       0         1        1         1
    287       0         1        1         1
    288       0         1        1         1
    289       0         1        1         1
    290       0         1        1         1
    291       0         1        1         1
    292       0         1        1         1
    293       0         1        1         1
    294       0         1        1         1
    295       0         1        1         1
    296       0         1        1         1
    297       0         1        1         1
    298       0         1        1         1
    299       0         1        1         1
    300       0         1        1         1
    301       0         1        1         1
    302       0         1        1         1
    303       0         1        1         1
    304       0         1        1         1
    305       0         1        1         1
    306       0         1        1         1
    307       0         1        1         1
    308       0         1        1         1
    309       0         1        1         1
    310       0         1        1         1
    311       0         1        1         1
    312       0         1        1         1
    313       0         1        1         1
    314       0         1        1         1
    315       0         1        1         1
    316       0         1        1         1
    317       0         1        1         1
    318       0         1        1         1
    319       0         1        1         1
    320       0         1        1         1
    321       0         1        1         1
    322       0         1        1         1
    323       0         1        1         1
    324       0         1        1         1
    325       0         1        1         1
    326       0         1        1         1
    327       0         1        1         1
    328       0         1        1         1
    329       0         1        1         1
    330       0         1        1         1
    331       0         1        1         1
    332       0         1        1         1
    333       0         1        1         1
    334       0         1        1         1
    335       0         1        1         1
    336       0         1        1         1
    337       0         1        1         1
    338       0         1        1         1
    339       0         1        1         1
    340       0         1        1         1
    341       0         1        1         1
    342       0         1        1         1
    343       0         1        1         1
    344       0         1        1         1
    345       0         1        1         1
    346       0         1        1         1
    347       0         1        1         1
    348       0         1        1         1
    349       0         1        1         1
    350       0         1        1         1
    351       0         1        1         1
    352       0         1        1         1
    353       0         1        1         1
    354       0         1        1         1
    355       0         1        1         1
    356       0         1        1         1
    357       0         1        1         1
    358       0         1        1         1
    359       0         1        1         1
    360       0         1        1         1
    361       0         1        1         1
    362       0         1        1         1
    363       0         1        1         1
    364       0         1        1         1
    365       0         1        1         1
    366       0         1        1         1
    367       0         1        1         1
    368       0         1        1         1
    369       0         1        1         1
    370       0         1        1         1
    371       0         1        1         1
    372       0         1        1         1
    373       0         1        1         1
    374       0         1        1         1
    375       0         1        1         1
    376       0         1        1         1
    377       0         1        1         1
    378       0         1        1         1
    379       0         1        1         1
    380       0         1        1         1
    381       0         1        1         1
    382       0         1        1         1
    383       0         1        1         1
    384       0         1        1         1
    385       0         1        1         1
    386       0         1        1         1
    387       0         1        1         1
    388       0         1        1         1
    389       0         1        1         1
    390       0         1        1         1
    391       0         1        1         1
    392       0         1        1         1
    393       0         1        1         1
    394       0         1        1         1
    395       0         1        1         1
    396       0         1        1         1
    397       0         1        1         1
    398       0         1        1         1
    399       0         1        1         1
    400       0         1        1         1
    401       0         1        1         1
    402       0         1        1         1
    403       0         1        1         1
    404       0         1        1         1
    405       0         1        1         1
    406       0         1        1         1
    407       0         1        1         1
    408       0         1        1         1
    409       0         1        1         1
    410       0         1        1         1
    411       0         1        1         1
    412       0         1        1         1
    413       0         1        1         1
    414       0         1        1         1
    415       0         1        1         1
    416       0         1        1         1
    417       0         1        1         1
    418       0         1        1         1
    419       0         1        1         1
    420       0         1        1         1
    421       0         1        1         1
    422       0         1        1         1
    423       0         1        1         1
    424       0         1        1         1
    425       0         1        1         1
    426       0         1        1         1
    427       0         1        1         1
    428       0         1        1         1
    429       0         1        1         1
    430       0         1        1         1
    431       0         1        1         1
    432       0         1        1         1
    433       0         1        1         1
    434       0         1        1         1
    435       0         1        1         1
    436       0         1        1         1
    437       0         1        1         1
    438       0         1        1         1
    439       0         1        1         1
    440       0         1        1         1
    441       0         1        1         1
    442       0         1        1         1
    443       0         1        1         1
    444       0         1        1         1
    445       0         1        1         1
    446       0         1        1         1
    447       0         1        1         1
    448       0         1        1         1
    449       0         1        1         1
    450       0         1        1         1
    451       0         1        1         1
    452       0         1        1         1
    453       0         1        1         1
    454       0         1        1         1
    455       0         1        1         1
    456       0         1        1         1
    457       0         1        1         1
    458       0         1        1         1
    459       0         1        1         1
    460       0         1        1         1
    461       0         1        1         1
    462       0         1        1         1
    463       0         1        1         1
    464       0         1        1         1
    465       0         1        1         1
    466       0         1        1         1
    467       0         1        1         1
    468       0         1        1         1
    469       0         1        1         1
    470       0         1        1         1
    471       0         1        1         1
    472       0         1        1         1
    473       0         1        1         1
    474       0         1        1         1
    475       0         1        1         1
    476       0         1        1         1
    477       0         1        1         1
    478       0         1        1         1
    479       0         1        1         1
    480       0         1        1         1
    481       0         1        1         1
    482       0         1        1         1
    483       0         1        1         1
    484       0         1        1         1
    485       0         1        1         1
    486       0         1        1         1
    487       0         1        1         1
    488       0         1        1         1
    489       0         1        1         1
    490       0         1        1         1
    491       0         1        1         1
    492       0         1        1         1
    493       0         1        1         1
    494       0         1        1         1
    495       0         1        1         1
    496       0         1        1         1
    497       0         1        1         1
    498       0         1        1         1
    499       0         1        1         1
    500       0         1        1         1
    501       0         1        1         1
    502       0         1        1         1
    503       0         1        1         1
    504       0         1        1         1
    505       0         1        1         1
    506       0         1        1         1
    507       0         1        1         1
    508       0         1        1         1
    509       0         1        1         1
    510       0         1        1         1
    511       0         1        1         1

**Comment by esar** [comment]
@xfce I made a mistake in the doc, the origin is at the top left of the screen, not at the bottom left as I wrote in the doc.

Other than the coordinates being wrong because of the bad doc, I can see a couple of minor issues:
1) With the rectangles that you have defined in area.conf you need to increase the divshift parameter from 3 to 4. For example, you have this rectangle:
0 1 27 34 3
This rectangle contains 16 scaled pixels, so you need divshift set to 4 so that it divides the summed pixel values by 16.

2) You can leave out the extra unused pixels from the output.conf file. This would be the same as setting the enabled column to 0 and the HDMI Light will not try to send data for them. 
How you have it now will still work, but it will be sending more data than it needs to.

When I created my config I found it useful to switch between 2 test images, one with horizontal coloured stripes, and another with vertical. That way I could check that the LED colours were in line with the TV. For example, something like this: https://en.wikipedia.org/wiki/SMPTE_color_bars#/media/File:SMPTE_Color_Bars.svg

**Comment by xfce** [comment]
@esar Thanks. fixed it
