### ISSUE TITLE
4K support 

### ISSUE THREAD

**Issue by xfce** [esar/hdmilight-v3#4]
Hi @esar ,do you have the plan to support 4K signal, If you have the plan, i would like to help with the PCBA design，and give the demo hardware for you😊

**Comment by esar** [comment]
Hi @xfce, no I don't currently have any plans to support 4k. I don't have a 4k TV. Maybe I might add support if I get a new TV in the future, but it won't be any time soon.

**Comment by wyntrblue** [comment]
Hi @esar this is a truely brilliant project. Don’t suppose you have moved to 4K since 2020?
